# Generated by Django 4.1.7 on 2023-03-30 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='call',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
