# Generated by Django 4.1.7 on 2023-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0004_remove_users_id_alter_users_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=10)),
            ],
        ),
    ]
