# Generated by Django 4.1.7 on 2023-04-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0005_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500000)),
                ('date', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
