# Generated by Django 4.1.7 on 2023-04-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0006_blogs_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
    ]
