# Generated by Django 4.1.7 on 2023-04-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0007_alter_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
