# Generated by Django 4.1.7 on 2023-04-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0008_alter_blogs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('following', models.CharField(max_length=100)),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='vlogapi.users')),
            ],
        ),
    ]
