# Generated by Django 4.1.7 on 2023-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0010_alter_followers_follower_alter_followers_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='view',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
