# Generated by Django 4.1.7 on 2023-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogapi', '0011_blogs_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('feedname', models.CharField(max_length=100)),
                ('feedurl', models.CharField(max_length=100)),
            ],
        ),
    ]
